- JadeMarble.podspec
- KeenSense.podspec
- NuguAgents.podspec
- NuguClientKit.podspec
- NuguCore.podspec
- NuguCore/Sources/NuguCore.swift
- NuguLoginKit.podspec
- NuguObjcUtils.podspec
- NuguServiceKit.podspec
- NuguUIKit.podspec
- NuguUtils.podspec
- OpusSDK.podspec
- SilverTray.podspec
- TycheSDK.podspec
- nugu-ios.xcodeproj/project.pbxproj
> 버전 업데이트 `1.10.2`

- .github/workflows/test_pull_request.yml
- `test_pull_request` 변경
- Carthage 제거로 스크립트 변경
> `test_pull_request` 변경

- Package.swift
- nugu-ios.xcodeproj/project.pbxproj
> 타겟버전을 iOS13 으로 변경

- NuguAgents/Sources/Extension/UpstreamEventSendable+Convenience.swift
- NuguCore/Sources/Context/ContextManageable.swift
- NuguCore/Sources/Context/ContextManager.swift
- NuguCore/Sources/Extension/Publishers+Convenience.swift
- nugu-ios.xcodeproj/project.pbxproj
- ContextManager내 RxSwift 제거
- async method를 사용해야하는 부분도 존재하긴 하지만, 우선적으로 RxSwift -> Combine으로 변경
> ContextManager내 RxSwift 제거

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/Directive/AsyncKey.swift
- NuguClientKit/Sources/Client/NuguClient+Builder.swift
- nugu-ios.xcodeproj/project.pbxproj
- AsyncKey 추가 및 ASRState의 조건 처리 변경
- busy 상태에서 AsyncKey의 dialogRequestId가 일치하고, state가 end가 되면 state를 idle로 변경
> AsyncKey 추가 및 ASRState의 조건 처리 변경

- NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/Chips/ChipsAgent.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
- NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgent.swift
- NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
- NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgent.swift
- NuguAgents/Sources/CapabilityAgents/Nudge/NudgeAgent.swift
- NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgent.swift
- NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
- NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
- NuguAgents/Sources/CapabilityAgents/Session/SessionAgent.swift
- NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
- NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
- NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/Utility/UtilityAgent.swift
- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
- NuguCore/Sources/Directive/BlockingPolicy.swift
- NuguCore/Sources/Directive/DirectiveSequencer.swift
- Blocking Policy 변경
- https://confluence.tde.sktelecom.com/display/ROMAINE/04.+Directive+Blocking+Policy
> Blocking Policy 변경

- NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgent.swift
- Permission.RequestPermission blocking policy 변경
> Permission.RequestPermission blocking policy 변경

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguClientKit/Sources/Client/NuguClient+Builder.swift
- 음성발화 이후로 asyncKey가 포함되어있지 않으면 state를 idle로 바꾸도록 변경
> 음성발화 이후로 asyncKey가 포함되어있지 않으면 state를 idle로 바꾸도록 변경

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/Permission/PermissionAgent.swift
- NuguCore/Sources/Directive/DirectiveSequencer.swift
- Blocking Policy 처리로직 개선 및 audioPlayer 보여지는 타이밍 변경
> Blocking Policy 처리로직 개선 및 audioPlayer 보여지는 타이밍 변경

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
TTS.Play directive를 취소할 경우 directiveSequencer에 동일한 dialogRequestId를 가진 directive도 취소하도록 변경
> TTS.Speak 취소 시 cancelDirective도 호출하도록 변경

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- asr focus state가 nothing이고 asr state일 때 아무동작도 안하도록 변경
> asr focus state가 nothing이고 asr state일 때 아무동작도 안하도록 변경

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- ASR Agent 내 AsyncKey로직 롤백
- AsyncKey로 인해서 asrState가 busy상태로 유지될 경우 stopListening 호출 시 event channel를 닫아버려서 사이드 이펙트 발생
- AsrState가 busy상태여서 focus를 놓지 않고 있음. TTS 등 directive처리가 느려져서 사용부분 전반적으로 문제가 발생함.
> ASR Agent 내 AsyncKey로직 롤백

- NuguCore/Sources/Network/Api/NuguApiProvider.swift
- 서버 내부의 처리가 지연되는 현상이 있어서 requestTimeout을 10초에서 20초로 변경
> requestTimeout을 20초로 변경

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSSpeakPayload.swift
- TTS.Speak directive payload 업데이트(text field optional로 변경)
> TTS.Speak directive payload 업데이트

- NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
- SystemAgent 내 warning Notification 추가
> SystemAgent 내 warning Notification 추가

- NuguCore/Sources/MediaPlayer/MediaPlayer.swift
> MediaPlayer Memory Leak 위험요소 제거

- NuguCore/Sources/MediaPlayer/MediaPlayer.swift
- timeControlStatus가 paused일 때에만 일시정지시키도록 수정
> timeControlStatus가 paused일 때에만 일시정지시키도록 수정

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
- nugu-ios.xcodeproj/project.pbxproj
- scripts/versionUpdate.sh
- 버전 업데이트(xcconfig 파일로 관리)
- 스크립트 업데이트
> update verion to `1.10.4`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgentProtocol.swift
- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/MediaPlayer/DataSource/MediaUrlDataSource.swift
- NuguCore/Sources/MediaPlayer/MediaPlayer.swift
- audio asset 캐싱옵션을 설정할 수 있도록 변경
- 특정 곡은 캐싱데이터가 이상하게 나옴
> audio asset 캐싱옵션을 설정할 수 있도록 변경

- NuguCore/Sources/Context/ContextManager.swift
> waitForAll제거

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Version 업데이트(1.10.7)

- NuguCore/Sources/Context/ContextManager.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.10.7`

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- JadeMarble/Sources/Util/RingBuffer.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- nugu-ios.xcodeproj/project.pbxproj
TycheEngine의 상태가 start로 변경되면 오디오 데이터를 서버로 전송하도록 변경
> ASRAgent 동작방식 변경

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Update version to '1.10.9'

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerPlayPayload.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlayEvent.swift
- Interface 업데이트(`1.10` -> `1.11`)
- Directive
- service object 추가 (subAgentId 포함)
- Play
- Event
- service object 추가 (subAgentId 포함)
- NextCommandIssued
- PreviousCommandIssued
- PlayBackFinished
- ProgressReportIntervalElapsed
- ElementSelected
> AudioPlayer Interface 1.11 업데이트

- NuguCore/Sources/MediaPlayer/MediaPlayer.swift
- MediaPlayer pendingProcess 수행 중 Race Condition 수정
> MediaPlayer pendingProcess 수행 중 Race Condition 수정

- NuguClientKit/Sources/Audio/ControlCenterManager.swift
- NuguClientKit/Sources/Audio/ControlCenterManagerDelegate.swift
- nugu-ios.xcodeproj/project.pbxproj
ControlCenterManagerDelegate 추가
> ControlCenterManagerDelegate 추가

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- NuguClientKit/Sources/Audio/ControlCenterManager.swift
- NuguClientKit/Sources/Audio/ControlCenterManagerDelegate.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
- nugu-ios.xcodeproj/project.pbxproj
> Release `1.10.11`

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/Opus/OpusPlayer.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
- NuguClientKit/Sources/Audio/AudioSessionManager.swift
- SilverTray/Sources/DataStreamPlayer.swift
- DataStreamPlayer에 gainController 추가
> DataStreamPlayer에 gainController 추가

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/Opus/OpusPlayer.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
- NuguClientKit/Sources/Audio/AudioSessionManager.swift
- NuguCore/Sources/NuguCore.swift
- SilverTray/Sources/DataStreamPlayer.swift
- SupportingFiles/shared.xcconfig
> release `1.11.0`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.11.1`

- NuguClientKit/Sources/Client/NuguClient.swift
- NuguClientKit/Sources/Configuration/ConfigurationStore.swift
- NuguCore/Sources/Common/NuguServerInfo.swift
- NuguCore/Sources/Network/Api/NuguApiProvider.swift
- l4switch address를 더이상 사용하지 않아서 코드 삭제
> 사용하지 않는 l4SwitchAddress 삭제

- KeenSense/Sources/KeywordDetector/TycheKeywordDetectorEngine.swift
- NuguClientKit/Sources/Audio/KeywordDetector/KeywordDetector.swift
- KeywordDetector에서 여러개의 키워드를 감지할 수 있도록 변경
- 하위호환성을 위해 keyword, keywords를 추가, 이후 keyword 제거 예정
> KeywordDetector에서 여러개의 키워드를 감지할 수 있도록 변경

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/Message/MessageAgent+Event.swift
- NuguAgents/Sources/CapabilityAgents/Message/MessageAgent.swift
- NuguAgents/Sources/CapabilityAgents/Message/MessageAgentDirectivePayload.swift
- NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent+Event.swift
- NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
- NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgentDirectivePayload.swift
PhoneCallAgent, MessageAgent에 serviceObject 추가 및 event에 바이패스
> PhoneCallAgent, MessageAgent에 serviceObject 추가 및 바이패스

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent+Event.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayAgent.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayClosePayload.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayControlPayload.swift
- NuguAgents/Sources/CapabilityAgents/Display/DisplayTemplate.swift
> service object 추가

- NuguAgents/Sources/CapabilityAgents/Display/DisplayTemplate.swift
> codingkey 가 잘못 들어가 있는 문제 수정

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentDelegate.swift
- nugu-ios.xcodeproj/project.pbxproj
> TTS Interface 업데이트(1.4)

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
ASRAgentProtocol에 delegate 누락 되어잇던 문제 수정
> ASRAgentProtocol에 delegate 누락 되어잇던 문제 수정

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.11.4`

- NuguAgentsTests/NuguAgentsTests.swift
- NuguCore/Sources/Common/NuguCoreError.swift
- NuguCore/Sources/Context/ContextManageable.swift
- NuguCoreTests/NuguCoreTests.swift
- nugu-ios.xcodeproj/project.pbxproj
- ContextManager 에서 combine을 사용할 수 있도록 수정
> ContextManager 에서 combine을 사용할 수 있도록 수정

- NuguAgents/Sources/CapabilityAgents/Interaction/InteractionControlConst.swift
- NuguAgents/Sources/CapabilityAgents/Interaction/InteractionControlManager.swift
- NuguAgentsTests/NuguAgentsTests.swift
- InteractionControlManager RxSwift > Combine으로 변경
- Test code 작성
> InteractionControlManager Combine으로 변경

- NuguCore/Sources/PlaySync/PlaySyncManager.swift
- NuguCoreTests/NuguCoreTests.swift
- PlaySyncManager RxSwift > Combine
- 테스트 코드 추가
> PlaySyncManager Combine으로 변경

- NuguCore/Sources/Directive/DirectiveSequencer.swift
> DirectiveSequencer RxSwift 제거

- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/StreamData/StreamDataRoutable.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
- device gateway address를 가져올 수 있는 메서드 추가
> device gateway address를 가져올 수 있는 메서드 추가

- NuguAgents/Sources/Extension/UpstreamEventSendable+Convenience.swift
- NuguAgentsTests/StreamDataRouterTests.swift
- NuguAgentsTests/TestDouble/DirectiveSequencer.swift
- NuguAgentsTests/TestDouble/NuguApiProvider.swift
- nugu-ios.xcodeproj/project.pbxproj
- SendEvent 전송 시 combine을 사용하도록 변경
> SendEvent 전송 시 combine을 사용하도록 변경

- NuguAgents/Sources/CapabilityAgents/PhoneCall/PhoneCallAgent.swift
> PhoneCallAgent Combine 적용

- NuguAgents/Sources/CapabilityAgents/Alerts/AlertsAgent.swift
> AlertAgent combine으로 변경

- NuguAgents/Sources/CapabilityAgents/Routine/RoutineAgent.swift
- RoutineAgent 내 RxSwift > Combine 으로 변경
> RoutineAgent combine으로 변경

- NuguAgents/Sources/CapabilityAgents/Messenger/MessengerAgent.swift
- MessengerAgent 내 Rxswift를 Combine으로 변경
> MessengerAgent Combine으로 변경

- NuguAgents/Sources/CapabilityAgents/MediaPlayer/MediaPlayerAgent.swift
- MediaPlayerAgent 내 RxSwift > Combine
> MediaPlayerAgent Combine으로 변경

- NuguAgents/Sources/CapabilityAgents/Text/TextAgent.swift
> TextAgent Combine으로 변경

- NuguAgents/Sources/CapabilityAgents/Sound/SoundAgent.swift
> SoundAgent Combine 적용

- NuguAgents/Sources/CapabilityAgents/Extension/ExtensionAgent.swift
> ExtensionAgent Combine 전환

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- RxSwift > Combine으로 변경
- var option과 self.option의 혼동과 코드 가독성을 높이기 위해서 변수 이름 변경, let if 문으로 변경했습니다.
https://github.com/AgentiOS/nugu-ios/blob/74ff8ba4a64efefe410317e07e803e8d217dd27b/NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift#L780-L790
> ASRAgent Combine 적용

- NuguAgents/Sources/CapabilityAgents/System/SystemAgent.swift
> SystemAgent RxSwift > Combine으로 변경

- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/NuguCore.swift
- NuguCore/Sources/StreamData/StreamDataRoutable.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
- SupportingFiles/shared.xcconfig
> Release `1.11.4`

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
> TTSAgent  RxSwift > Combine으로 변경

- NuguAgentsTests/TestDouble/NuguApiProvider.swift
- NuguCore/Sources/Network/Api/NuguApiProvidable.swift
- NuguCore/Sources/Network/Api/NuguApiProvider.swift
- NuguApiProvidable 에 combine 추가
- TC 작성을 위한 작업
> NuguApiProvidable 에 combine 추가

- NuguCore/Sources/StreamData/ServerSentEventReceiver.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
- NuguCoreTests/ServerSentEventReceiverTests.swift
- NuguCoreTests/TestDouble/NuguApiProvider.swift
- nugu-ios.xcodeproj/project.pbxproj
- ServerSentEventReceiver 내 RxSwift를 Combine으로 전환
> ServerSentEventReceiver 내 RxSwift를 Combine으로 전환

- NuguCore/Sources/StreamData/Model/ServerSentEventReceivable.swift
- NuguCore/Sources/StreamData/ServerSentEventReceiver.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
- NuguCoreTests/ServerSentEventReceiverTests.swift
- NuguCoreTests/StreamDataRouterTests.swift
- NuguCoreTests/TestDouble/DirectiveSequencer.swift
- nugu-ios.xcodeproj/project.pbxproj
- StreamDataRouter 내 RxSwift을 Combine으로 변경
> StreamDataRouter 내 RxSwift 제거

- NuguAgents/Sources/CapabilityAgents/Session/SessionConst.swift
- NuguAgents/Sources/CapabilityAgents/Session/SessionManageable.swift
- NuguAgents/Sources/CapabilityAgents/Session/SessionManager.swift
- NuguAgentsTests/SessionManagerTests.swift
- nugu-ios.xcodeproj/project.pbxproj
- SessionManager 내 RxSwift를 Combine으로 변경
> SessionManager 내 RxSwift를 Combine으로 변경

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguClientKit/Sources/Client/NuguClient+Builder.swift
mic를 열 때 audioSession을 활성화하도록 변경
> mic를 열 때 audioSession을 활성화하도록 변경

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
* AudioPlayerAgent 내 RxSwift를 Combine으로 전환
> AudioPlayerAgent 내 RxSwift를 Combine으로 전환

- NuguClientKit/Sources/Client/NuguClient+Builder.swift
- NuguCore/Sources/Directive/DirectivePreProcessable.swift
- NuguCore/Sources/StreamData/StreamDataPreProcessor.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
- nugu-ios.xcodeproj/project.pbxproj
> DirectivePreProcessor 추가

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlayEvent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlaylistEvent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+SettingsEvent.swift
- AudioPlayerAgent event payload 에 service field 추가
> AudioPlayerAgent event payload 에 service field 추가

- SilverTray/Sources/Engine/AudioEngineManager.swift
> AudioEngineManager 내 log 개선

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
> ASRAgent Notification에 amplitude 추가

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
> audioSession mode가 voiceChat이면 default로 전환

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
> clean up audiosession if audioPlayerAgent enters foreground state

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgentProtocol.swift
- allowSpeak interface 추가
- false로 전환 시 기존 tts도 cancel
> allowSpeak 추가

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguCore/Sources/Context/ContextInfo.swift
- NuguCore/Sources/Context/ContextManager.swift
- compactContextPayload를 각 agent에서 설정할 수 있도록 변경
- 기존에는 compactContext의 경우 version만 포함시켰지만 ttsAgent에서 allowSpeak도 추가되었는데 향후에도 이런 스펙이 포함될 가능성도 있고 각 agent마다 필수 payload가 달라질 수 있음
> compactContextPayload를 각 agent에서 설정할 수 있도록 변경

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.2.2`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.2.3`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+BadgeButtonEvent.swift
> badgeButtonEvent 에 servicePayload추가

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+BadgeButtonEvent.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.2.3`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.2.5`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+LyricsEvent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+PlayEvent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+RequestPlayEvent.swift
- NuguAgents/Sources/CapabilityAgents/AudioPlayer/Event/AudioPlayerAgent+SettingsEvent.swift
> AudioPlayerAgent event payload에 service field 추가

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/ClientEndPointDetector.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectable.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/Adapter/TycheEndPointDetectorEngineAdapter.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/EndPointDetectorEngineProtocol.swift
> postponeSlienceTimeout 추가

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.2.6`

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/ClientEndPointDetector.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectable.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/Adapter/TycheEndPointDetectorEngineAdapter.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/EndPointDetectorEngineProtocol.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.2.6`

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/ClientEndPointDetector.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectable.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/Adapter/TycheEndPointDetectorEngineAdapter.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/EndPointDetectorEngineProtocol.swift
> change method(postpone timeout -> reset timeout)

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/ClientEndPointDetector.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectable.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/Adapter/TycheEndPointDetectorEngineAdapter.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/EndPointDetector/EndPointDetectorEngine/EndPointDetectorEngineProtocol.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.1`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트`1.13.1`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.2`

- NuguCore/Sources/Directive/DirectiveSequencer.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.2`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.3`

- JadeMarble/Sources/TycheEndPointDetectorEngine.swift
- fix EPD Engine ringbuffer send logic
- start state일 때 ringbuffer의 모든 데이터를 전송하고 시작
> fix EPD Engine ringbuffer send logic

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.4`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.5`

- NuguClientKit/Sources/Business/DialogStateAggregator.swift
- chips 정책 변경
- chips target이 listen, speaking 이 동시에 들어올 수 있어서 list로 관리
- listen, speaking을 보여주면 list에서 제거(일회성이기 때문)
> improve chips logic

- NuguClientKit/Sources/Business/DialogStateAggregator.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.5`

- NuguClientKit/Sources/Client/NuguClient.swift
- NuguClient 내 로그 추가
- dialogState가 변경되었음에도 Notification이 수신되지 않는 케이스가 발견되어서 로그 추가
> NuguClient 내 로그 추가

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
> fix SpeechState data race

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.7`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.8`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.9`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerDirectivePreProcessor.swift
- NuguCore/Sources/StreamData/Model/AsyncKey.swift
- NuguCore/Sources/StreamData/Model/Downstream.swift
- NuguCore/Sources/StreamData/StreamDataRouter.swift
> parsing logic 개선

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- asrResult가 바뀌는 타이밍에는 이미 asrRequest가 nil이어서 didSet이 동작안함
- 전체적인 개선 필요
> ASR recognizeFailed 로직 개선

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
> sourceType이 attachment일 때 replacePlayer가 동작하지 않던 문제 수정

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.10`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.11`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayerAgent.swift
> voiceChat 일 때 AudioPlayerAgent 내 AudioSession 처리

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.13`

- NuguAgents/Sources/CapabilityAgents/AudioPlayer/AudioPlayer.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.13`

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguClientKit/Sources/Client/NuguClient.swift
> 마이크를 열 때 오디오세션을 변경시키지 않도록 수정

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguClientKit/Sources/Client/NuguClient+Builder.swift
> stopRecognize 호출 시 마지막으로 시작한 recognize에 연관된 directive를 취소시킨다

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguClientKit/Sources/Client/NuguClient+Builder.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.15`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.16`

- NuguClientKit/Sources/Client/NuguClient.swift
> audioDeactivate delay 조절 함수 추가

- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.16`

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguCore/Sources/Focus/FocusChannelPriority.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.18`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.19`

- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSAgent.swift
- NuguAgents/Sources/CapabilityAgents/TextToSpeech/TTSPlayer.swift
- NuguCore/Sources/MediaPlayer/MediaPlayable.swift
> TTS attachment가 speak 보다 먼저 처리될 경우 실행하지 않도록 수정

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 업데이트 버전 `1.12.20`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.21`

- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
> BackgroundFocusHolder 에 log 추가

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.22`

- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent+Event.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgent.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRAgentProtocol.swift
- NuguAgents/Sources/CapabilityAgents/AutomaticSpeechRecognition/ASRInitiator.swift
- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- ASRInitiator.wakeUpWord 에 eventIdentifier 추가
> wakeup state에 eventIdentifier 추가

- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
- NuguClientKit/Sources/Client/NuguClient.swift
- ASRResult가 error일 경우 handlingPendingDirectives가 제거되지않는 문제
> BackgroundFocusHolder가 포커스를 내려놓지 않는 문제 수정

- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
- NuguClientKit/Sources/Client/NuguClient.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.23`

- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
- TTS.Speak directive에 대해서만 backgroundFocusHolder 정책을 받도록 변경
> TTS.Speak directive에 대해서만 backgroundFocusHolder 정책을 받도록 변경

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.24`

- NuguClientKit/Sources/Business/BackgroundFocusHolder.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.12.24`

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.12.25`

- NuguCore/Sources/Directive/DirectiveSequencer.swift
> cancel directive일 경우, handlingDirectives와 blockedDirectives 항목에서 제거

- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> 버전 업데이트 `1.13.2`

- NuguClientKit/Sources/Audio/SpeechRecognizerAggregator.swift
- NuguCore/Sources/NuguCore.swift
- SupportingFiles/shared.xcconfig
> Release `1.13.2`
